version: "3.8"
services:
  db:
    image: postgres:16.3-alpine3.20
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - D:/.pgdata:/var/lib/postgresql/data
    restart: always
  pg_admin:
    image: dpage/pgadmin4:8.8
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
    ports:
      - 5050:80
    restart: always
    # volumes:
    #  - ./data/pg_admin:/var/lib/pgadmin